# Generated by Django 5.0.7 on 2024-10-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.IntegerField(null=True, unique=True)),
                ('articleType_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BaseColour',
            fields=[
                ('id', models.IntegerField(null=True, unique=True)),
                ('baseColour_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.IntegerField(null=True, unique=True)),
                ('gender_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.IntegerField(null=True, unique=True)),
                ('master_category_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.IntegerField(null=True, unique=True)),
                ('season_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.IntegerField(null=True, unique=True)),
                ('sub_category_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('usage', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('productDisplayName', models.CharField(max_length=255)),
                ('imageName', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('articleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProducts.articletype')),
                ('baseColour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProducts.basecolour')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProducts.gender')),
                ('masterCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProducts.mastercategory')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProducts.season')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProducts.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAllTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProducts.products')),
            ],
        ),
    ]
