# Generated by Django 5.0.7 on 2024-10-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
