# Generated by Django 5.0.7 on 2024-10-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageProducts', '0001_initial'),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amt', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField()),
                ('purchase_date', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('canceled', 'Canceled')], default='pending', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProducts.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.create_user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProducts.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.create_user')),
            ],
        ),
        migrations.CreateModel(
            name='popoularItemByView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProducts.products')),
            ],
        ),
    ]
